### ISSUE TITLE
Error when starting a game

### ISSUE THREAD

**Issue by monam7** [holgern/steemmonsters#15]
"Ranking" for example is working fine and I see all my stats.
But when I try to run "play random" or "play MYDECK" it gives me an error code like:

Traceback (most recent call last):
  File "steemmonsters.py", line 1310, in <module>
    main()
  File "steemmonsters.py", line 1306, in main
    smprompt.cmdloop()
  File "C:\..............n\Python37-32\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "C:\..............\Python37-32\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "steemmonsters.py", line 846, in do_play
    mana_cap = self.settings["ranked_settings"]["mana_cap"]
KeyError: 'ranked_settings'

I think there is a problem with ranking or mana settings? I only edited the config.json.
Would be nice if somebody knows whats the problem! :)

**Comment by deniskariuki** [comment]
Hi, I am having a similar issue to this and I am hoping you got a solution @monam7. Would love to know how to make it work.
